import { emptyFilter, filterHasClauses } from "./filter";
import type { BrowserView, LogSet, Project, Tab } from "./types";
import { DEFAULT_HEADER_COLOR, DEFAULT_HEADER_PATHS } from "./types";

export function normalizeLogSet(set: LogSet): LogSet {
  return {
    ...set,
    headerPaths: Array.isArray(set.headerPaths) && set.headerPaths.length > 0
      ? set.headerPaths.slice(0, 3)
      : [...DEFAULT_HEADER_PATHS],
    headerColor: set.headerColor || DEFAULT_HEADER_COLOR,
    columns: Array.isArray(set.columns) ? set.columns : [],
    sortBy: set.sortBy,
    defaultPinnedPaths: Array.isArray(set.defaultPinnedPaths) ? set.defaultPinnedPaths : [],
    hiddenPaths: Array.isArray(set.hiddenPaths) ? set.hiddenPaths : [],
  };
}

export function normalizeView(view: BrowserView, fallbackSetId: string): BrowserView {
  const raw = view as BrowserView & { search?: string; logSetId: string | "all" };
  const logSetId = !raw.logSetId || raw.logSetId === "all" ? fallbackSetId : raw.logSetId;
  let filter = view.filter ?? emptyFilter();
  const legacySearch = typeof raw.search === "string" ? raw.search.trim().toLowerCase() : "";
  if (!filterHasClauses(filter) && LEGACY_LEVELS.has(legacySearch)) {
    filter = {
      kind: "group",
      join: "and",
      children: [{ kind: "clause", path: "level", op: "eq", value: legacySearch, valueTo: "" }],
    };
  }
  return {
    id: view.id,
    name: view.name,
    logSetId,
    columns: view.columns ?? [],
    sortBy: view.sortBy,
    filter,
  };
}

const LEGACY_LEVELS = new Set(["error", "warn", "warning", "info", "debug", "fatal", "trace"]);

/** Import/empty-project “All logs” rows — source browse replaced these. */
export function isAutoGeneratedView(view: BrowserView, logSets: LogSet[]): boolean {
  if (filterHasClauses(view.filter)) return false;
  const name = view.name.trim().toLowerCase();
  if (name === "all logs" || name === "imported") return true;
  const set = logSets.find((s) => s.id === view.logSetId);
  return Boolean(set && name === set.name.trim().toLowerCase());
}

function tabKey(tab: Tab): string {
  if (tab.kind === "canvas") return `canvas:${tab.canvasId}`;
  if (tab.kind === "source") return `source:${tab.logSetId}`;
  if (tab.kind === "browser") return `browser:${tab.viewId}`;
  return "settings";
}

export function normalizeProject(project: Project): Project {
  const fallbackSetId = project.logSets[0]?.id ?? "";
  const logSets = project.logSets.map(normalizeLogSet);
  const keptViews = project.views
    .map((v) => normalizeView(v, fallbackSetId))
    .filter((v) => v.logSetId)
    .filter((v) => !isAutoGeneratedView(v, logSets));
  const keptIds = new Set(keptViews.map((v) => v.id));
  const droppedById = new Map(
    project.views.filter((v) => !keptIds.has(v.id)).map((v) => [v.id, v.logSetId]),
  );

  const openTabs: Tab[] = [];
  const seen = new Set<string>();
  for (const tab of project.openTabs) {
    let next: Tab | null = tab;
    if (tab.kind === "browser" && droppedById.has(tab.viewId)) {
      const logSetId = droppedById.get(tab.viewId);
      next = logSetId ? { id: tab.id, kind: "source", logSetId } : null;
    }
    if (!next) continue;
    if (next.kind === "browser" && !keptIds.has(next.viewId)) continue;
    if (next.kind === "source") {
      const sourceId = next.logSetId;
      if (!logSets.some((s) => s.id === sourceId)) continue;
    }
    const key = tabKey(next);
    if (seen.has(key)) continue;
    seen.add(key);
    openTabs.push(next);
  }

  let activeTabId = project.activeTabId;
  if (activeTabId && !openTabs.some((t) => t.id === activeTabId)) {
    const old = project.openTabs.find((t) => t.id === activeTabId);
    if (old?.kind === "browser" && droppedById.has(old.viewId)) {
      const logSetId = droppedById.get(old.viewId);
      activeTabId = openTabs.find((t) => t.kind === "source" && t.logSetId === logSetId)?.id
        ?? openTabs[openTabs.length - 1]?.id
        ?? null;
    } else {
      activeTabId = openTabs[openTabs.length - 1]?.id ?? null;
    }
  }

  return {
    ...project,
    logSets,
    views: keptViews,
    openTabs,
    activeTabId,
  };
}

export function projectNormalizedDirty(before: Project, after: Project): boolean {
  return (
    JSON.stringify(before.views) !== JSON.stringify(after.views) ||
    JSON.stringify(before.openTabs) !== JSON.stringify(after.openTabs) ||
    JSON.stringify(before.logSets) !== JSON.stringify(after.logSets)
  );
}
